import { randomBytes } from 'crypto'
import type { GuestFeeWithDeductions } from 'types/revenue'

export const revenueId: string = randomBytes(16).toString()

export const totalChannelCommissionFixture = 33.36 // Using 3% of totalGrossRevenue
export const totalGrossRevenueFixture = 1112 // accommodation revenue: $750

const guestFees: GuestFeeWithDeductions[] = [
  {
    id: '1',
    name: 'Cleaning fee',
    value: 100,
    taxable: true,
    pmcShare: 50,
    type: 'GUEST_FEE',
    revenueId: revenueId,
    createdAt: new Date(),
    updatedAt: new Date(),
    unit: 'PerStay',
    deductions: [
      {
        id: randomBytes(16).toString(),
        description: 'Municipal tax',
        value: 8,
        type: 'TAX',
        revenueFeeId: '1',
        createdAt: new Date(),
        updatedAt: new Date(),
        revenueId: null,
      },
      {
        id: randomBytes(16).toString(),
        description: 'County tax',
        value: 4,
        type: 'TAX',
        revenueFeeId: '1',
        createdAt: new Date(),
        updatedAt: new Date(),
        revenueId: null,
      },
      {
        id: randomBytes(16).toString(),
        description: 'State tax',
        value: 10,
        type: 'TAX',
        revenueFeeId: '1',
        createdAt: new Date(),
        updatedAt: new Date(),
        revenueId: null,
      },
    ],
  },
  {
    id: '2',
    name: 'Pet fee',
    value: 80,
    taxable: true,
    pmcShare: 75,
    type: 'GUEST_FEE',
    revenueId: revenueId,
    createdAt: new Date(),
    updatedAt: new Date(),
    unit: 'PerStay',
    deductions: [
      {
        id: randomBytes(16).toString(),
        description: 'Municipal tax',
        value: 6.4,
        type: 'TAX',
        revenueFeeId: '2',
        createdAt: new Date(),
        updatedAt: new Date(),
        revenueId: null,
      },
      {
        id: randomBytes(16).toString(),
        description: 'County tax',
        value: 3.2,
        type: 'TAX',
        revenueFeeId: '2',
        createdAt: new Date(),
        updatedAt: new Date(),
        revenueId: null,
      },
      {
        id: randomBytes(16).toString(),
        description: 'State tax',
        value: 8,
        type: 'TAX',
        revenueFeeId: '2',
        createdAt: new Date(),
        updatedAt: new Date(),
        revenueId: null,
      },
    ],
  },
  {
    id: '3',
    name: 'Internet',
    value: 50,
    taxable: true,
    pmcShare: 100,
    type: 'GUEST_FEE',
    revenueId: revenueId,
    createdAt: new Date(),
    updatedAt: new Date(),
    unit: 'PerStay',
    deductions: [
      {
        id: randomBytes(16).toString(),
        description: 'Municipal tax',
        value: 4,
        type: 'TAX',
        revenueFeeId: '3',
        createdAt: new Date(),
        updatedAt: new Date(),
        revenueId: null,
      },
      {
        id: randomBytes(16).toString(),
        description: 'County tax',
        value: 2,
        type: 'TAX',
        revenueFeeId: '3',
        createdAt: new Date(),
        updatedAt: new Date(),
        revenueId: null,
      },
      {
        id: randomBytes(16).toString(),
        description: 'State tax',
        value: 5,
        type: 'TAX',
        revenueFeeId: '3',
        createdAt: new Date(),
        updatedAt: new Date(),
        revenueId: null,
      },
    ],
  },
  {
    id: '4',
    name: 'Daily Newspaper delivery',
    value: 132,
    taxable: false,
    pmcShare: 40,
    type: 'GUEST_FEE',
    revenueId: revenueId,
    createdAt: new Date(),
    updatedAt: new Date(),
    unit: 'PerStay',
    deductions: [],
  },
]

export const guestFeesFixture = (): GuestFeeWithDeductions[] => {
  return guestFees
}
