const amenities = [
  { typeIds: ['ACC1'], name: 'Airport', categories: ['Location features'] },
  { typeIds: ['ACC114'], name: 'Duty free', categories: ['Entertainment'] },
  { typeIds: ['ACC119'], name: 'Covered lanai or gazebo ', categories: ['Outdoor'] },
  { typeIds: ['ACC123'], name: 'Rural', categories: ['Location features'] },
  { typeIds: ['ACC203'], name: 'Ferry', categories: ['Parking & facilities', 'Services'] },
  { typeIds: ['ACC24'], name: 'Local hospital', categories: ['Location features'] },
  { typeIds: ['ACC25'], name: 'Lake', categories: ['Location features'] },
  { typeIds: ['ACC28'], name: 'Marina', categories: ['Location features', 'Parking & facilities'] },
  { typeIds: ['ACC31'], name: 'Mountain', categories: ['Location features'] },
  { typeIds: ['ACC32'], name: 'Attractions museums', categories: ['Location features'] },
  { typeIds: ['ACC33'], name: 'Near ocean', categories: ['Location features'] },
  { typeIds: ['ACC40'], name: 'Resort', categories: ['Location features'] },
  { typeIds: ['ACC42'], name: 'River', categories: ['Location features'] },
  { typeIds: ['ACC45', 'RST156', 'HAC6171', 'HAC6170'], name: 'Ski-in / ski-out', categories: ['Location features', 'Popular'] },
  { typeIds: ['ACC54'], name: 'Waterpark', categories: ['Nearby activities', 'Nearby activities'] },
  { typeIds: ['ACC56'], name: 'Winery tours', categories: ['Nearby activities'] },
  { typeIds: ['ACC57'], name: 'Zoo', categories: ['Nearby activities'] },
  { typeIds: ['ACC65'], name: 'Shopping', categories: ['Location features'] },
  { typeIds: ['ACC74'], name: 'Bay', categories: ['Location features'] },
  { typeIds: ['ACC90', 'RST134', 'RMA6051'], name: 'Garden or backyard', categories: ['Location features', 'Outdoor'] },
  { typeIds: ['HAC101'], name: 'Wheelchair accessible', categories: ['Accessibility'] },
  { typeIds: ['HAC173', 'RMA6099'], name: 'Breakfast', categories: ['Services'] },
  { typeIds: ['HAC186'], name: 'Street parking', categories: ['Parking & facilities'] },
  { typeIds: ['HAC199'], name: 'Train', categories: ['Location features'] },
  { typeIds: ['HAC21', 'HAC168'], name: 'Coin laundry', categories: ['Parking & facilities', 'Bedroom & laundry', 'Location features'] },
  { typeIds: ['HAC233'], name: 'Tennis', categories: ['Parking & facilities', 'Nearby activities'] },
  { typeIds: ['HAC237'], name: 'Horseback riding', categories: ['Sports'] },
  { typeIds: ['HAC238'], name: 'Ocean front', categories: ['Location features'] },
  { typeIds: ['HAC239'], name: 'Beachfront', categories: ['Location features'] },
  { typeIds: ['HAC241'], name: 'Iron and board', categories: ['Popular', 'Bedroom & laundry'] },
  { typeIds: ['HAC242', 'RMA166'], name: 'Heating', categories: ['Heating & cooling'] },
  { typeIds: ['HAC273'], name: 'Water skiing', categories: ['Nearby activities'] },
  { typeIds: ['HAC283'], name: 'Luggage dropoff allowed', categories: ['Services'] },
  { typeIds: ['HAC33'], name: 'Elevator', categories: ['Parking & facilities', 'Accessibility'] },
  { typeIds: ['HAC348'], name: 'Health & beauty spa', categories: ['Location features'] },
  { typeIds: ['HAC42'], name: 'Free parking', categories: ['Parking & facilities'] },
  { typeIds: ['HAC44'], name: 'Game room', categories: ['Entertainment'] },
  { typeIds: ['HAC49'], name: 'Heated pool', categories: ['Popular', 'Parking & faciliites'] },
  { typeIds: ['HAC5109', 'HAC5110', 'HAC5111', 'HAC5112'], name: 'Swimming', categories: ['Nearby activities'] },
  { typeIds: ['HAC54'], name: 'Indoor pool', categories: ['Popular', 'Parking & facilities'] },
  { typeIds: ['HAC55', 'RST104'], name: 'Hot tub', categories: ['Popular', 'Parking & facilities'] },
  { typeIds: ['HAC6014', 'HAC15'], name: 'Car rental available', categories: ['Services'] },
  { typeIds: ['HAC6020'], name: 'Boat', categories: ['Nearby activities'] },
  { typeIds: ['HAC6025'], name: 'Pack n play travel crib', categories: ['Family'] },
  { typeIds: ['HAC6027'], name: 'Games', categories: ['Entertainment'] },
  { typeIds: ['HAC6029'], name: 'Car necessary', categories: ['Accessibility'] },
  { typeIds: ['HAC6030'], name: 'Car not necessary', categories: ['Accessibility'] },
  { typeIds: ['HAC6031'], name: 'Car recommended', categories: ['Accessibility'] },
  { typeIds: ['HAC6033'], name: 'Ev charger', categories: ['Parking & facilities'] },
  { typeIds: ['HAC6034'], name: 'Long term stays allowed', categories: ['Services'] },
  { typeIds: ['HAC6035'], name: 'Mid-stay clean available', categories: ['Services'] },
  { typeIds: ['HAC6036'], name: 'Beach essentials', categories: ['Outdoor'] },
  { typeIds: ['HAC6037'], name: 'Wide hallway clearance', categories: ['Accessibility'] },
  { typeIds: ['HAC6038'], name: 'Home: step free access', categories: ['Accessibility'] },
  { typeIds: ['HAC6039'], name: 'Path to entrance lit at night', categories: ['Home safety', 'Accessibility'] },
  { typeIds: ['HAC6040'], name: 'Home: wide doorway', categories: ['Accessibility'] },
  { typeIds: ['HAC6041'], name: 'Flat smooth pathway to front door', categories: ['Accessibility'] },
  { typeIds: ['HAC6042'], name: 'Disabled parking spot', categories: ['Accessibility'] },
  { typeIds: ['HAC6044', 'HAC202'], name: 'Cycling', categories: ['Nearby activities'] },
  { typeIds: ['HAC6050', 'HAC6052'], name: 'Concierge', categories: ['Services'] },
  { typeIds: ['HAC6066'], name: 'Fire pit', categories: ['Outdoor'] },
  { typeIds: ['HAC6067', 'HAC345', 'RST35', 'HAC6184'], name: 'Gym / fitness center', categories: ['Location features', 'Parking & facilities'] },
  { typeIds: ['HAC6072'], name: 'Lake access', categories: ['Location features'] },
  { typeIds: ['HAC6073'], name: 'Local laundromat', categories: ['Location features'] },
  { typeIds: ['HAC6082'], name: 'Outdoor dining area', categories: ['Outdoor', 'Kitchen & dining', 'Entertainment'] },
  { typeIds: ['HAC6087', 'ACC55', 'HAC6091'], name: 'Waterfront', categories: ['Location features'] },
  { typeIds: ['HAC6099', 'RMA6092'], name: 'High chair', categories: ['Family'] },
  { typeIds: ['HAC61'], name: 'Massage', categories: ['Services'] },
  { typeIds: ['HAC6106', 'HAC234'], name: 'Watersports', categories: ['Nearby activities'] },
  { typeIds: ['HAC6107'], name: 'Babysitter recommendations', categories: ['Services'] },
  { typeIds: ['HAC6115', 'HAC6002'], name: 'Private chef', categories: ['Services'] },
  { typeIds: ['HAC6141'], name: 'Electric profiling bed', categories: ['Accessibility'] },
  { typeIds: ['HAC6142'], name: 'Common space: step free access', categories: ['Accessibility'] },
  { typeIds: ['HAC6143'], name: 'Common space: wide doorway', categories: ['Accessibility'] },
  { typeIds: ['HAC6144'], name: 'Mobile hoist', categories: ['Accessibility'] },
  { typeIds: ['HAC6145'], name: 'Pool hoist', categories: ['Accessibility'] },
  { typeIds: ['HAC6146'], name: 'Ceiling hoist', categories: ['Accessibility'] },
  { typeIds: ['HAC6147'], name: 'Garage', categories: ['Parking & facilities'] },
  { typeIds: ['HAC6148'], name: 'Foosball', categories: ['Entertainment'] },
  { typeIds: ['HAC6149'], name: 'Music library', categories: ['Entertainment'] },
  { typeIds: ['HAC6150'], name: 'Deepsea fishing', categories: ['Nearby activities'] },
  { typeIds: ['HAC6151'], name: 'Fishing: bay', categories: ['Nearby activities'] },
  { typeIds: ['HAC6152'], name: 'Fishing: freshwater', categories: ['Nearby activities'] },
  { typeIds: ['HAC6153'], name: 'Fishing: surf', categories: ['Nearby activities'] },
  { typeIds: ['HAC6156'], name: 'Pier fishing', categories: ['Nearby activities'] },
  { typeIds: ['HAC6158'], name: 'Ski lift privileges optional', categories: ['Nearby activities'] },
  { typeIds: ['HAC6159'], name: 'Spelunking', categories: ['Nearby activities'] },
  { typeIds: ['HAC6160'], name: 'Deadbolt lock', categories: ['Home Safety'] },
  { typeIds: ['HAC6161'], name: 'Emergency contact', categories: ['Home safety'] },
  { typeIds: ['HAC6162'], name: 'Emergency exit route', categories: ['Home safety'] },
  { typeIds: ['HAC6163'], name: 'Medical emergency contact', categories: ['Home safety'] },
  { typeIds: ['HAC6164'], name: 'Police emergency contact', categories: ['Home safety'] },
  { typeIds: ['HAC6165'], name: 'Antiquing', categories: ['Entertainment'] },
  { typeIds: ['HAC6166'], name: 'Wildlife viewing', categories: ['Entertainment'] },
  { typeIds: ['HAC6167'], name: 'Theme park', categories: ['Nearby activities', 'Location features'] },
  { typeIds: ['HAC6168'], name: 'Golf course front', categories: ['Location features'] },
  { typeIds: ['HAC6169'], name: 'Downtown', categories: ['Location features'] },
  { typeIds: ['HAC6172'], name: 'Village', categories: ['Location features'] },
  { typeIds: ['HAC6173'], name: 'Town', categories: ['Location features'] },
  { typeIds: ['HAC6174'], name: 'Watersports gear', categories: ['Outdoor'] },
  { typeIds: ['HAC6175'], name: 'Snowsports gear', categories: ['Outdoor'] },
  { typeIds: ['HAC6176'], name: 'Outdoor veranda', categories: ['Outdoor'] },
  { typeIds: ['HAC6177', 'HAC6183', 'HAC6154', 'RST34', 'HAC6182'], name: 'Golf', categories: ['Nearby activities'] },
  { typeIds: ['HAC6178'], name: 'Restaurant', categories: ['Location features'] },
  { typeIds: ['HAC6179'], name: 'Highway', categories: ['Location features'] },
  { typeIds: ['HAC6180', 'HAC272'], name: 'Skiing', categories: ['Nearby activities'] },
  { typeIds: ['HAC6181'], name: 'Bar', categories: ['Kitchen & dining'] },
  { typeIds: ['HAC6185'], name: 'Chauffeur', categories: ['Services'] },
  { typeIds: ['HAC6186', 'HAC6155'], name: 'Mountaineering', categories: ['Nearby activities'] },
  { typeIds: ['HAC6187'], name: 'Kayak / canoe', categories: ['Nearby activities'] },
  { typeIds: ['HAC6188'], name: 'Rafting', categories: ['Nearby activities'] },
  { typeIds: ['HAC63'], name: 'Paid parking (off-site)', categories: ['Parking & facilities'] },
  { typeIds: ['HAC64'], name: 'Paid parking (on-site)', categories: ['Parking & facilities'] },
  { typeIds: ['HAC66'], name: 'Outdoor pool', categories: ['Popular', 'Outdoor', 'Parking & facilities'] },
  { typeIds: ['HAC68'], name: 'Parking', categories: ['Parking & facilities'] },
  { typeIds: ['HAC71', 'HAC6086'], name: 'Communal pool', categories: ['Popular', 'Parking & facilities'] },
  { typeIds: ['HAC79'], name: 'Sauna', categories: ['Parking & facilities'] },
  { typeIds: ['HAC9'], name: 'BBQ area', categories: ['Outdoor'] },
  { typeIds: ['RMA100'], name: 'Smoke detector', categories: ['Home safety'] },
  { typeIds: ['RMA104'], name: 'Stereo', categories: ['Entertainment'] },
  { typeIds: ['RMA105'], name: 'Stove', categories: ['Kitchen & dining'] },
  { typeIds: ['RMA107'], name: 'Telephone', categories: ['Internet & office'] },
  { typeIds: ['RMA117'], name: 'Video games', categories: ['Entertainment'] },
  { typeIds: ['RMA123', 'HAC179', 'RMA6126'], name: 'Wifi', categories: ['Internet & office', 'Popular'] },
  { typeIds: ['RMA13'], name: 'Bathtub', categories: ['Bathroom'] },
  { typeIds: ['RMA142', 'RMA97', 'RMA15'], name: 'Shower', categories: ['Bathroom'] },
  { typeIds: ['RMA16'], name: 'Bidet', categories: ['Bathroom'] },
  { typeIds: ['RMA163'], name: 'Dvd player', categories: ['Entertainment'] },
  { typeIds: ['RMA167'], name: 'Toaster', categories: ['Kitchen & dining'] },
  { typeIds: ['RMA19'], name: 'Coffee maker', categories: ['Popular', 'Kitchen & dining'] },
  { typeIds: ['RMA190'], name: 'Breakfast included in price', categories: ['Services'] },
  { typeIds: ['RMA2'], name: 'Air conditioning', categories: ['Heating & cooling'] },
  { typeIds: ['RMA210', 'RMA18'], name: 'Cable or satellite tv', categories: ['Entertainment', 'Internet & office'] },
  { typeIds: ['RMA218'], name: 'Video library', categories: ['Entertainment'] },
  { typeIds: ['RMA223'], name: 'Mountain view', categories: ['Location features'] },
  { typeIds: ['RMA224'], name: 'Ocean view', categories: ['Location features'] },
  { typeIds: ['RMA242'], name: 'Hot water', categories: ['Bathroom'] },
  { typeIds: ['RMA245'], name: 'Private pool', categories: ['Popular', 'Parking & facilities'] },
  { typeIds: ['RMA251'], name: 'Tv', categories: ['Entertainment'] },
  { typeIds: ['RMA32'], name: 'Dishwasher', categories: ['Kitchen & dining'] },
  { typeIds: ['RMA41'], name: 'Fireplace', categories: ['Heating & cooling'] },
  { typeIds: ['RMA50'], name: 'Hair-dryer', categories: ['Bathroom'] },
  { typeIds: ['RMA5085'], name: 'Dining area', categories: ['Kitchen & dining'] },
  { typeIds: ['RMA5103'], name: 'Game console', categories: ['Entertainment'] },
  { typeIds: ['RMA5147'], name: 'Grab rails in toilet', categories: ['Accessibility'] },
  { typeIds: ['RMA5154'], name: 'Shower chair', categories: ['Accessibility'] },
  { typeIds: ['RMA5177'], name: 'Shampoo', categories: ['Bathroom'] },
  { typeIds: ['RMA54'], name: 'Internet', categories: ['Popular', 'Internet & office'] },
  { typeIds: ['RMA55'], name: 'Iron', categories: ['Bedroom & laundry'] },
  { typeIds: ['RMA56'], name: 'Ironing board', categories: ['Bedroom & laundry'] },
  { typeIds: ['RMA59'], name: 'Kitchen', categories: ['Kitchen & dining'] },
  { typeIds: ['RMA6'], name: 'Baby monitor', categories: ['Family'] },
  { typeIds: ['RMA6001'], name: 'Towels', categories: ['Bedroom & laundry'] },
  { typeIds: ['RMA6012'], name: 'Beach view', categories: ['Location features'] },
  { typeIds: ['RMA6017'], name: 'Water view', categories: ['Location features'] },
  { typeIds: ['RMA6021'], name: 'Fire extinguisher', categories: ['Home safety'] },
  { typeIds: ['RMA6027'], name: 'Golf course view', categories: ['Location features'] },
  { typeIds: ['RMA6029'], name: 'Lake view', categories: ['Location features'] },
  { typeIds: ['RMA6034', 'RMA149'], name: 'Dryer', categories: ['Bedroom & laundry'] },
  { typeIds: ['RMA6035'], name: 'Hangers', categories: ['Bedroom & laundry'] },
  { typeIds: ['RMA6036'], name: 'Laptop-friendly', categories: ['Internet & office'] },
  { typeIds: ['RMA6037'], name: 'Essentials (towels, bed sheets, soap, toilet paper, and pillows)', categories: ['Popular', 'Bedroom & laundry'] },
  { typeIds: ['RMA6039'], name: 'Balcony', categories: ['Outdoor'] },
  { typeIds: ['RMA6058'], name: 'Bed linens', categories: ['Bedroom & laundry'] },
  { typeIds: ['RMA6066', 'HAC6127'], name: 'House cleaning included', categories: ['Services'] },
  { typeIds: ['RMA6067'], name: 'Carbon monoxide detector', categories: ['Home safety'] },
  { typeIds: ['RMA6068'], name: 'First aid kit', categories: ['Home safety'] },
  { typeIds: ['RMA6073'], name: 'Lock on bedroom door', categories: ['Home safety'] },
  { typeIds: ['RMA6075'], name: 'Private entrance', categories: ['Location features'] },
  { typeIds: ['RMA6076'], name: 'Outlet covers', categories: ['Family'] },
  { typeIds: ['RMA6077'], name: 'Baby bath', categories: ['Family'] },
  { typeIds: ['RMA6078'], name: 'Stair gates', categories: ['Family'] },
  { typeIds: ['RMA6079'], name: 'Window guards', categories: ['Family'] },
  { typeIds: ['RMA6080'], name: 'Corner guards', categories: ['Family'] },
  { typeIds: ['RMA6081'], name: 'Fireplace guards', categories: ['Family'] },
  { typeIds: ['RMA6082'], name: 'Room darkening shades', categories: ['Bedroom & laundry'] },
  { typeIds: ['RMA6083'], name: 'Childrens dinnerware', categories: ['Family', 'Kitchen & dining'] },
  { typeIds: ['RMA6084'], name: 'Childrens books and toys', categories: ['Family'] },
  { typeIds: ['RMA6088', 'HAC6128'], name: 'House cleaning optional', categories: ['Services'] },
  { typeIds: ['RMA6091'], name: 'Wood stove', categories: ['Kitchen & dining'] },
  { typeIds: ['RMA6094'], name: 'Dining room', categories: ['Kitchen & dining'] },
  { typeIds: ['RMA6095'], name: 'Spices', categories: ['Kitchen & dining'] },
  { typeIds: ['RMA6098'], name: 'Wheelchair in-accessible', categories: ['Accessibility'] },
  { typeIds: ['RMA6100'], name: 'Extra pillows and blankets', categories: ['Bedroom & laundry'] },
  { typeIds: ['RMA6101'], name: 'Ethernet connection', categories: ['Internet & office'] },
  { typeIds: ['RMA6102'], name: 'Pocket wifi', categories: ['Internet & office'] },
  { typeIds: ['RMA6103'], name: 'Cooking basics: Pots and pans, oil, salt and pepper', categories: ['Popular', 'Kitchen & dining'] },
  { typeIds: ['RMA6104'], name: 'Changing table', categories: ['Family'] },
  { typeIds: ['RMA6105'], name: 'Bedroom: step free access', categories: ['Accessibility'] },
  { typeIds: ['RMA6106'], name: 'Wide clearance to bed', categories: ['Accessibility'] },
  { typeIds: ['RMA6107'], name: 'Bedroom: wide doorway', categories: ['Accessibility'] },
  { typeIds: ['RMA6108'], name: 'Accessible height bed', categories: ['Accessibility'] },
  { typeIds: ['RMA6109'], name: 'Bathroom: step free access', categories: ['Accessibility'] },
  { typeIds: ['RMA6110'], name: 'Grab rails in shower', categories: ['Accessibility'] },
  { typeIds: ['RMA6111'], name: 'Accessible height toilet', categories: ['Accessibility'] },
  { typeIds: ['RMA6112'], name: 'Roll-in shower', categories: ['Accessibility'] },
  { typeIds: ['RMA6113'], name: 'Bathroom: wide doorway', categories: ['Accessibility'] },
  { typeIds: ['RMA6114'], name: 'Tub with shower bench', categories: ['Accessibility'] },
  { typeIds: ['RMA6115'], name: 'Wide clearance to shower and toilet', categories: ['Accessibility'] },
  { typeIds: ['RMA6116'], name: 'Handheld shower head', categories: ['Bathroom', 'Accessibility'] },
  { typeIds: ['RMA6117'], name: 'Single level home', categories: ['Accessibility'] },
  { typeIds: ['RMA6146', 'RMA6033'], name: 'Washer', categories: ['Bedroom & laundry'] },
  { typeIds: ['RMA6148', 'RMA6042', 'RMA5207'], name: 'Private living room', categories: ['Parking & facilities'] },
  { typeIds: ['RMA6149', 'RMA271'], name: 'Toilet', categories: ['Bathroom'] },
  { typeIds: ['RMA6150', 'RMA155'], name: 'Combination tub shower', categories: ['Bathroom'] },
  { typeIds: ['RMA6151'], name: 'Outdoor shower', categories: ['Bathroom', 'Outdoor'] },
  { typeIds: ['RMA6154'], name: 'Books', categories: ['Entertainment'] },
  { typeIds: ['RMA6155'], name: 'Toys', categories: ['Entertainment'] },
  { typeIds: ['RMA6158'], name: 'Indoor fireplace', categories: ['Entertainment', 'Heating & cooling'] },
  { typeIds: ['RMA68'], name: 'Microwave', categories: ['Kitchen & dining'] },
  { typeIds: ['RMA7'], name: 'Patio', categories: ['Outdoor'] },
  { typeIds: ['RMA77'], name: 'Oven', categories: ['Kitchen & dining'] },
  { typeIds: ['RMA8'], name: 'BBQ grill', categories: ['Kitchen & dining', 'Outdoor'] },
  { typeIds: ['RMA88'], name: 'Refrigerator', categories: ['Kitchen & dining'] },
  { typeIds: ['RMA89'], name: 'Ice maker', categories: ['Kitchen & dining'] },
  { typeIds: ['RMA9', 'RMA57'], name: 'Jetted tub', categories: ['Bathroom'] },
  { typeIds: ['RMA98'], name: 'Dishes and silverware: Bowls, chopsticks, plates, cups, etc.', categories: ['Kitchen & dining'] },
  { typeIds: ['RST101'], name: 'Windsurfing', categories: ['Nearby activities'] },
  { typeIds: ['RST105'], name: 'Hunting', categories: ['Nearby activities'] },
  { typeIds: ['RST108'], name: 'Mountain climbing', categories: ['Nearby activities'] },
  { typeIds: ['RST111'], name: 'Pool table', categories: ['Entertainment'] },
  { typeIds: ['RST112'], name: 'Rock climbing', categories: ['Nearby activities'] },
  { typeIds: ['RST116'], name: 'Surfing', categories: ['Nearby activities'] },
  { typeIds: ['RST117'], name: 'Ping pong table', categories: ['Entertainment', 'Parking & facilities'] },
  { typeIds: ['RST120'], name: 'Snowmobiling', categories: ['Nearby activities'] },
  { typeIds: ['RST127'], name: 'Bird watching', categories: ['Nearby activities'] },
  { typeIds: ['RST13'], name: 'Cross country skiing', categories: ['Nearby activities'] },
  { typeIds: ['RST133'], name: 'Gambling', categories: ['Entertainment'] },
  { typeIds: ['RST137'], name: 'Ice skating', categories: ['Nearby activities'] },
  { typeIds: ['RST151'], name: 'Outlet shopping', categories: ['Location features', 'Nearby activities'] },
  { typeIds: ['RST160'], name: 'Snorkeling & diving', categories: ['Nearby activities'] },
  { typeIds: ['RST169'], name: 'Outdoor bike', categories: ['Parking & facilities'] },
  { typeIds: ['RST173'], name: 'Historic', categories: ['Location features'] },
  { typeIds: ['RST175'], name: 'Romantic', categories: ['Location features'] },
  { typeIds: ['RST177'], name: 'Eco tourism', categories: ['Location features'] },
  { typeIds: ['RST179'], name: 'Paddle boating', categories: ['Nearby activities'] },
  { typeIds: ['RST180'], name: 'Sledding', categories: ['Nearby activities'] },
  { typeIds: ['RST182'], name: 'Whale watching', categories: ['Nearby activities'] },
  { typeIds: ['RST20'], name: 'Sports fishing', categories: ['Nearby activities'] },
  { typeIds: ['RST25'], name: 'Fly fishing', categories: ['Nearby activities'] },
  { typeIds: ['RST4'], name: 'Basketball court', categories: ['Parking & facilities'] },
  { typeIds: ['RST5', 'ACC5'], name: 'Beach', categories: ['Location features'] },
  { typeIds: ['RST60'], name: 'Hiking', categories: ['Nearby activities'] },
  { typeIds: ['RST63'], name: 'Jet skiing', categories: ['Nearby activities'] },
  { typeIds: ['RST65'], name: 'Kayaking', categories: ['Nearby activities'] },
  { typeIds: ['RST68'], name: 'Mountain biking', categories: ['Nearby activities'] },
  { typeIds: ['RST7'], name: 'Boating', categories: ['Nearby activities'] },
  { typeIds: ['RST73'], name: 'Parasailing', categories: ['Nearby activities'] },
  { typeIds: ['RST79'], name: 'Whitewater rafting', categories: ['Nearby activities'] },
  { typeIds: ['RST80'], name: 'Sailing', categories: ['Nearby activities'] },
  { typeIds: ['RST82'], name: 'Scuba or snorkeling', categories: ['Nearby activities'] },
  { typeIds: ['RST86'], name: 'Snorkeling', categories: ['Nearby activities'] },
  { typeIds: ['RST87'], name: 'Snowboarding', categories: ['Nearby activities'] },
  { typeIds: ['RST96'], name: 'Water tubing', categories: ['Nearby activities'] },
  { typeIds: ['RMA85'], name: 'Private bathroom', categories: ['Bathroom'] },
]

export default amenities
